### ISSUE TITLE
DRF returning HTML on 404 even with drf-standardized-errors installed

### ISSUE THREAD

**Issue by scottgigante** [ghazi-git/drf-standardized-errors#44] opened 2023-08-10 15:22 UTC
I've noticed that the standardized errors don't work if the route doesn't exist. I've made a minimum reproducible example based on the DRF tutorial, which successfully returns the standardized error if you ask for a primary key that doesn't exist:
```
➜  curl -H "Accept: application/json" "http://127.0.0.1:8000/users/-1/"
{"type":"client_error","errors":[{"code":"not_found","detail":"Not found.","attr":null}]}%
```
but still returns html if you ask for a route that doesn't exist
```
➜  curl -H "Accept: application/json" "http://127.0.0.1:8000/user/2/"

<!doctype html>
<html lang="en">
<head>
  <title>Not Found</title>
</head>
<body>
  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
</body>
</html>
```

[mre.zip](https://github.com/ghazi-git/drf-standardized-errors/files/12314475/mre.zip)

**Comment by ghazi-git** [comment] 2023-08-10 21:10
Thanks for raising the issue @scottgigante and providing a sample project.

The problem is that requests to non-existing routes do not reach drf, [they are handled by django](https://stackoverflow.com/questions/50791946/django-rest-framework-does-not-intercept-404-exceptions-and-outputs-html-instead). So, the drf-standardized-errors exception handler of is never called.

To return the expected format, you can create a custom [handler404](https://docs.djangoproject.com/en/dev/topics/http/views/#customizing-error-views) that returns the json you want.

This issue got me thinking: what should drf-standardized-errors do about error responses returned by django without reaching drf? like this one or those that happen in middleware... At the very least, some documentation is in order. Maybe provide default error handlers (400,403,404,500) matching what django provides out of the box?

**Comment by scottgigante** [comment] 2023-08-10 22:10
That would be great! On my end it appears this works -- though I'm not entirely sure as I'm not certain how to trigger core Django exceptions for anything other than 404.
```
# project/app/exceptions.py
import drf_standardized_errors.handler
from rest_framework.decorators import api_view

@api_view()
def error_handler(request, exception):
    """
    Generic Django error handler.
    """
    return drf_standardized_errors.handler.exception_handler(exception, {'request': request})
```
and then
```
# project/project/urls.py
handler400 = "app.exceptions.error_handler"
handler403 = "app.exceptions.error_handler"
handler404 = "app.exceptions.error_handler"
handler500 = "app.exceptions.error_handler"
```

**Comment by ghazi-git** [comment] 2023-08-11 05:52
reusing the exception handler in the error handler seems like a nice idea. For now, there is a small issue: for 500 errors, you might see duplicate errors in sentry and duplicate error logs. That's because the handler sends the got_request_exception and django also does that as well, and sentry relies on that to [report errors](https://github.com/getsentry/sentry-python/blob/f1fb5e1db50a58271270a10526b3e7a0b9ac5348/sentry_sdk/integrations/django/__init__.py#L166)

**Comment by scottgigante** [comment] 2023-08-11 14:00
Good point. Not a huge issue but a little suboptimal. I'd be interested if you come up with something better!

**Comment by ghazi-git** [comment] 2023-09-27 16:17
I went ahead and documented this issue in [the readme](https://github.com/ghazi-git/drf-standardized-errors/commit/17868b9988b010865fafd5b4825bdca9e05ecf85) and linked to this issue.

I'm closing the issue as resolved as the solution is up to the developer. [Scott's answer](https://github.com/ghazi-git/drf-standardized-errors/issues/44#issuecomment-1673981989) is a good start assuming the project provides a backend API only.

**Closed by ghazi-git** 2023-09-27 16:17 UTC
