### ISSUE TITLE
ExceptionFormatter ignores ErrorDetail with an empty detail message

### ISSUE THREAD

**Issue by kietheros** [ghazi-git/drf-standardized-errors#82] opened 2024-08-10 06:16 UTC
https://github.com/ghazi-git/drf-standardized-errors/blob/e4f20b656609059553b0dacde13d7d9f0099f24a/drf_standardized_errors/formatter.py#L112

If my code raises APIException(""), it will be ignored.
```python
try:
	func()  # could raise an Exception with empty message
except Exception as ex:
	raise APIException(str(ex))
```

**Comment by ghazi-git** [comment] 2024-08-10 16:12
Thank you for raising the issue and identifying the root cause @kietheros. The fix will be part of the next release.

**Closed** 2024-08-10 16:15 UTC
